FIX for #20: Cannot find icon: /Resources/icons/Maker_workbench_icon.svg
URJCMakerGroup/MakerWorkbench pull request #21
Opened 2021-07-18 00:13 UTC by allanlaal

2021-07-18 00:13 UTC, allanlaal commented
tested and works!

2021-07-23 07:05 UTC, davidmubernal commented
Thank you very much @allanlaal  for your contribution.
I haven't had time to check it out yet. I hope to make time to test and merge it this weekend.

2022-01-22 19:10 UTC, tjleon1 requested changes
This did not actually work for me when I tested it.  I found that properly enunciating the filepath worked:

`    Icon = FreeCAD.getUserAppDataDir()+"Mod"+"/MakerWorkbench/Resources/icons/Maker_workbench_icon.svg"
`

2022-02-11 17:35 UTC, evanhorn commented
This also did not work for me, so I (shamelessly) borrowed from other workbenches to find a solution.

2022-03-24 22:01 UTC, tjleon1 commented on InitGui.py
> +    Icon = "./Resources/icons/Maker_workbench_icon.svg"
This is the way to properly enunciate the filepath:
`Icon = FreeCAD.getUserAppDataDir()+"Mod"+"/MakerWorkbench/Resources/icons/Maker_workbench_icon.svg"`

2022-04-26 18:51 UTC, closed without merging